# Generated by Django 3.2.12 on 2022-02-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permset',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
